// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPBf-OCLX_y8MMkEIfE-uWWWY0k1tE-b0',
    appId: '1:266664404354:android:e36ac88b7d0d0e26e05b9b',
    messagingSenderId: '266664404354',
    projectId: 'five-s-app-1',
    storageBucket: 'five-s-app-1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByyGgtUQICp5IGZ-saXiIS0LOcgLiIJCY',
    appId: '1:266664404354:web:2dfb53de0780ac67e05b9b',
    messagingSenderId: '266664404354',
    projectId: 'five-s-app-1',
    authDomain: 'five-s-app-1.firebaseapp.com',
    storageBucket: 'five-s-app-1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByyGgtUQICp5IGZ-saXiIS0LOcgLiIJCY',
    appId: '1:266664404354:web:0fb187d42abdf7a7e05b9b',
    messagingSenderId: '266664404354',
    projectId: 'five-s-app-1',
    authDomain: 'five-s-app-1.firebaseapp.com',
    storageBucket: 'five-s-app-1.firebasestorage.app',
  );

}